Repository digital-explorers-2/eesti-explorer, pull requests merged in 2024-05, with the labels that each got.

#40 docs/ align images to vertical placement
  README.md
Labels: design

#41 chore:adds shadcn ui and removes unnecessary code in files
  app/page.tsx
  components/Header.tsx
  components/tutorial/ConnectSupabaseSteps.tsx
  my-app/.eslintrc.json
  my-app/.gitignore
  my-app/README.md
  my-app/app/favicon.ico
  my-app/app/globals.css
  my-app/app/layout.tsx
  my-app/app/page.tsx
  my-app/next.config.mjs
  my-app/package-lock.json
  my-app/package.json
  my-app/postcss.config.mjs
  my-app/public/next.svg
  my-app/public/vercel.svg
  my-app/tailwind.config.ts
  my-app/tsconfig.json
  package-lock.json
Labels: setup

#43 feat:(landing page):
  .env.example
  app/layout.tsx
  app/page.tsx
  components/LandingPage/Navbar.tsx
  components/MediumButton.tsx
  components/images/hero-section.png
  components/images/logo.png
Labels: frontend

#47 Feat/create landing page
  app/globals.css
  app/page.tsx
  components.json
  components/LandingPage/Destinations.tsx
  components/LandingPage/Home.tsx
  components/LandingPage/Navbar.tsx
  components/images/LandingPage/destination1.png
  components/images/LandingPage/destination2.png
  components/images/LandingPage/destination3.png
  components/images/LandingPage/destination4.png
  components/images/LandingPage/destination5.png
  components/images/LandingPage/destination6.png
  components/images/LandingPage/hero-image.png
  components/images/LandingPage/logo.png
  components/ui/badge.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: frontend

#56 feat: add profile page
  app/profile/page.tsx
  components/ui/avatar.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  package-lock.json
  package.json
Labels: frontend

#59 Feat(footer)
  app/page.tsx
  components/Footer.tsx
  components/LandingPage/Subscribe.tsx
Labels: frontend

#63 Feat edit register page front end
  app/login/page.tsx
Labels: frontend

#64 fix(destinations):
  app/destinations/page.tsx
Labels: frontend

#73 Feat/about page:
  app/about/page.tsx
  app/destinations/page.tsx
  app/globals.css
  app/profile/page.tsx
  components/LandingPage/About.tsx
  components/LandingPage/Destinations.tsx
  components/LandingPage/Home.tsx
  components/gates.png
  components/ui/dialog.tsx
  gates.png
  my-app/.eslintrc.json
  my-app/.gitignore
  my-app/README.md
  my-app/app/favicon.ico
  my-app/app/globals.css
  my-app/app/layout.tsx
  my-app/app/page.tsx
  my-app/next.config.mjs
  my-app/package-lock.json
  my-app/package.json
  my-app/postcss.config.mjs
  my-app/tailwind.config.ts
  my-app/tsconfig.json
  package-lock.json
  package.json
Labels: frontend

#76 Fix/profile: fetches data from auth in supabase using google client, also fixes navbar avatar to fetch data from db
  app/profile/page.tsx
  components/Navbar.tsx
Labels: frontend

#78 docs: adds admin mockups
  README.md
Labels: documentation
